title: Humanities Data
description: ENGL 6701
theme: just-the-docs

url: https://lindsaythomas.net/engl6701s24

aux_links:
  Source: https://github.com/lcthomas/engl6701s24
  Course Canvas site: https://canvas.cornell.edu/courses/62495
  
heading_anchors: false
